name: Push Gem

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      # Set up
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252 # v1.229.0
        with:
          bundler-cache: true
          ruby-version: ruby
      - name: Git config
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Configure trusted publishing credentials
        uses: rubygems/configure-rubygems-credentials@v1.0.0
        with:
          gem-server: https://058c-90-191-171-38.ngrok-free.app
      - name: Run release rake task
        run: bundle exec rake release
        env:
          RUBYGEMS_HOST: https://058c-90-191-171-38.ngrok-free.app
